# Generated by Django 4.0.2 on 2022-02-04 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acronyms", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="acronym",
            unique_together={("acronym", "definition")},
        ),
    ]
