# Generated by Django 4.0.2 on 2022-02-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acronyms", "0002_alter_acronym_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acronym",
            options={"ordering": ["acronym"]},
        ),
    ]
