# Generated by Django 4.0.2 on 2022-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acronyms", "0004_acronym_create_by_acronym_create_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="acronym",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
