# Generated by Django 5.0.3 on 2025-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acronyms", "0006_alter_acronym_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="acronym",
            name="delete_by",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="acronym",
            name="delete_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acronym",
            name="update_by",
            field=models.CharField(default="Ryan Cheley", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="acronym",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
