# Generated by Django 5.0.3 on 2025-12-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acronyms", "0007_acronym_delete_by_acronym_delete_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acronym",
            name="delete_by",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
