name: Prod CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22          
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            git clone git@github.com:ryancheley/acronym-slackbot.git

            source venv/bin/activate

            rsync -av --delete --exclude=.env acronym-slackbot/* core

            pip -q install -r core/requirements.txt

            python core/manage.py migrate

            python core/manage.py collectstatic --noinput -v0

            sudo systemctl daemon-reload
            sudo systemctl restart slackbot
            
            rm -rf acronym-slackbot
