name: Prod CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy code
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            git clone git@github.com:ryancheley/acronym-slackbot.git

            source venv/bin/activate

            cp -r acronym-slackbot/* core

            pip -q install -r core/requirements.txt

            python core/manage.py migrate

            python core/manage.py collectstatic --noinput -v0

            sudo systemctl daemon-reload
            sudo systemctl restart slackbot
            rm -rf acronym-slackbot
