name: Prod CI

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: deploy code
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            rm -rf acronym-slackbot
            git clone git@github.com:ryancheley/acronym-slackbot.git

            source /home/slackbot/venv/bin/activate

            cd /home/slackbot/

            rm -rf /home/slackbot/core

            cp -r /root/acronym-slackbot/ /home/slackbot/core

            cp /home/slackbot/.env /home/slackbot/core/core/.env

            pip -q install -r /home/slackbot/core/requirements.txt

            python /home/slackbot/core/manage.py migrate

            mkdir /home/slackbot/core/static

            python /home/slackbot/core/manage.py collectstatic --noinput -v0

            systemctl daemon-reload
            systemctl restart slackbot